name: Deploy Angular App to cPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: fintech-apps

      - name: Build Angular App
        run: npm run build -- --configuration production --base-href=/
        working-directory: fintech-apps

      - name: Deploy to cPanel via FTP
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.CPANEL_FTP_HOST }}
          user: ${{ secrets.CPANEL_FTP_USER }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          localDir: fintech-apps/dist/fintech-apps
          remoteDir: ${{ secrets.CPANEL_TARGET_DIR }}

